AWSTemplateFormatVersion: 2010-09-09
Resources:
  UbuntuTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-Ubuntu'
      LaunchTemplateData:
        Placement:
          Tenancy: dedicated
        ImageId: ami-0688ba7eeeeefe3cd
        InstanceType: t2.micro
  WindowsTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-Windows'
      LaunchTemplateData:
        Placement:
          Tenancy: dedicated
        ImageId: !Sub 'ami-050f7a9b9b315c6c3'
        InstanceType: t2.micro
