AWSTemplateFormatVersion: 2010-09-09
Description: "This is my first bucket!!"
Conditions:
  IsPreferredRegion: !Equals
    - !Ref Region
    - us-east-1
Resources:
  UzoS3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !If 
        - IsPreferredRegion 
        - !Join ["-", [!Ref AWS::AccountId, !Ref Name]]
        - !Join ["-", [!Ref AWS::Region, !Ref Name]]
Parameters:
  Name:
    Type: String
    Description: "Name of the bucket"
  Region:
    Type: String
    Description: "Region to deploy the stack to"